---
title: "Review Text Clustering with R"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tm)
library(Matrix)
library(plyr)
library(stats)
library(ggpubr)
library(factoextra)
```

## Load Data

```{r}
# Load pre processed sparse matrix
sparse_matrix <- readRDS("processed/sparse_matrix.rds")
```

## Reduce the dimensionality of sparse_matrix
* Remove terms that occur less than n times
```{r}
# Sort the sparse matrix by term frequency in descending order
sparse_matrix <- sparse_matrix[order(rowSums(sparse_matrix), decreasing = TRUE), ]
# Get top 100 words by frequency
top_100_words <- rownames(sparse_matrix)[1:100]
# Remove the words day and month
top_100_words <- top_100_words[!top_100_words %in% c("day", "month", "year", "week", "time", "hour", "minute", "second", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december")]

# Get a sparce matrix with only top 100 words
sparse_matrix <- sparse_matrix[top_100_words, ]
```


## Hierarchical Clustering
Clustering using dendrogram
```{r}
distance <- dist(scale(sparse_matrix))
hc <- hclust(distance, method = "ward.D2") # D or D2
# Display the dendrogram

png("images/dendogram.png", width = 12, height = 6, units = "in", res = 300)
plot(hc, hang=-1)
rect.hclust(hc, k = 8, border = "red")
dev.off()
```

## Non-Hierarchical Clustering
Clustering using k-means
```{r}
t_sparse <- t(sparse_matrix)
set.seed(0)
k <- 3
kmeans_model <- kmeans(t_sparse, k)

# Display the cluster centers
kmeans_model$centers

# Display the cluster membership
kmeans_model$cluster
```