
install.packages("languageserver", repos = "https://cloud.r-project.org/")
install.packages("tidyverse", repos = "https://cloud.r-project.org/")
install.packages("jsonlite", repos = "https://cloud.r-project.org/")
install.packages("markdown", repos = "https://cloud.r-project.org/")
install.packages("ggpubr", repos = "https://cloud.r-project.org/")
install.packages("Matrix", repos = "https://cloud.r-project.org/")
install.packages("nloptr", repos = "https://cloud.r-project.org/")
install.packages("vader", repos = "https://cloud.r-project.org/")
install.packages("plyr", repos = "https://cloud.r-project.org/")
install.packages("tm", repos = "https://cloud.r-project.org/")
install.packages("dotenv", repos = "https://cloud.r-project.org/")
install.packages("e1071", repos = "https://cloud.r-project.org/")
install.packages("caret", repos = "https://cloud.r-project.org/")
install.packages("caTools", repos = "https://cloud.r-project.org/")
install.packages("kernlab", repos = "https://cloud.r-project.org/")
install.packages("httpgd", repos = "https://cloud.r-project.org/")
install.packages("dendextend", repos = "https://cloud.r-project.org/")
install.packages("cluster", repos = "https://cloud.r-project.org/")
install.packages("clValid", repos = "https://cloud.r-project.org/")
install.packages("RWeka", repos = "https://cloud.r-project.org/")
install.packages("rJava", repos = "https://cloud.r-project.org/")
remotes::install_github("cran/DMwR")
