---
title: "Review Text Clustering with R"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tm)
library(Matrix)
library(plyr)
library(stats)
library(ggpubr)
library(factoextra)
```

## Load Data

```{r}
# Load pre processed sparse matrix
sparse_matrix <- readRDS("processed/sparse_matrix.rds")
```

## Reduce the dimensionality of sparse_matrix
* Remove terms that occur less than n times
```{r}
# Play around with n
n <- 2000
sparse_matrix <- sparse_matrix[rowSums(sparse_matrix) >= n, ]
```


## Hierarchical Clustering
Clustering using dendrogram
```{r}
distance <- dist(scale(sparse_matrix))
hc <- hclust(distance, method = "ward.D2") # D or D2
# Display the dendrogram
plot(hc, hang=-1)
rect.hclust(hc, k = 3)
```

## Non-Hierarchical Clustering
Clustering using k-means
```{r}
t_sparse <- t(sparse_matrix)
set.seed(0)
k <- 3
kmeans_model <- kmeans(t_sparse, k)

# Display the cluster centers
kmeans_model$centers

# Display the cluster membership
kmeans_model$cluster
```