# Lexicon Sentiments Analysis Predictive Performance
```{r}
library(caret)
library(dplyr)
library(caTools)
library(DMwR)
library(e1071)
library(parallel)
library(caTools)
library(naivebayes)
```

## Function definition
```{r}
# Function to retrieve the data
get_data <- function(drug_reviews, sentiment_rds) {
    # Read the data
    rds <- readRDS(sentiment_rds)
    ge <- read.csv(drug_reviews)
    # Merge the data
    data <- cbind(ge, rds)
    # Return the data
    return(data)
}

# Function to return data with only 'Birth Control' reviews
filter_birth_control <- function(data) {
    data <- data[data$condition == "Birth Control", ]
    return(data)
}

# Function to remove columns
remove_columns_vader <- function(data) {
    data <- select(data, 1, -2:-9, 10:ncol(data))
    return(data)
}

remove_columns <- function(data) {
    data <- data[, c("rating_type", "ave_sentiment")]
    return(data)
}

# Function to format the data types
format_dtypes <- function(data) {
    data$rating_type <- as.factor(data$rating_type)
    data <- data %>% mutate_if(is.integer, as.numeric)
    return(data)
}

# Function to filter out bad values
filter_out_bad_vals <- function(data) {
    bad_rows <- apply(
        data, 1,
        function(x) any(is.na(x)) | any(is.nan(x)) | any(is.infinite(x))
    )
    clean_df <- data[!bad_rows, ]
    return(clean_df)
}

# Function to split the data
split_data <- function(data, split_ratio = 0.7, stratified = TRUE) {
    # TODO: Generalise target variable
    if (stratified) {
        # Split with createDataPartition function
        indexes <- createDataPartition(
            data$rating_type,
            p = split_ratio,
            list = FALSE,
            times = 1
        )
        train_data <- data[indexes, ]
        test_data <- data[-indexes, ]
        return(list(train_data, test_data))
    }

    # Split randomly
    if(is.null(data)) {
        stop("The dataframe is empty.")
    }
    tot_rows <- nrow(data)
    indexes <- sample(1:tot_rows, size = 0.8 * nrow(data))
    train_data <- data[indexes, ]
    test_data <- data[-indexes, ]
    return(list(train_data, test_data))
}


# Function to scale and center the data
scale_and_center <- function(train_test) {
    train_data <- train_test[[1]]
    test_data <- train_test[[2]]

    print(head(train))
    preprocess <- preProcess(train_data[, -1], method = c("center", "scale"))
    train[, -1] <- predict(preprocess, train[, -1])
    test[, -1] <- predict(preprocess, test[, -1])
    return(list(train_data, test_data))
}

# Function to perform SMOTE on the data
smote <- function(train_test, perc_over = 100, k = 5) {
    train_data <- train_test[[1]]
    test_data <- train_test[[2]]
    train_data <- SMOTE(
        rating_type ~ .,
        data = train_data,
        perc.over = perc_over,
        k = k
    )
    return(list(train_data, test_data))
}

# Function to perform stratified k-fold cross-validation
stratified_k_fold_cv <- function(train_test,
                                 k = 10,
                                 parallel = FALSE) {
    control <- trainControl(
        method = "cv",
        number = k,
        classProbs = TRUE,
        allowParallel = parallel
    )
    return(control)
}

train_model <- function(control,
                        train_test,
                        method = "svmLinear",
                        preProcess = c(),
                        tuneLength = 0,
                        verbose = FALSE) {
    
    train_data <- train_test[[1]]
    model <- train(
        rating_type ~ .,
        data = train_data,
        method = method,
        tuneLength = tuneLength,
        trControl = control,
        preProcess = preProcess,
        metric = "ROC",

    )
    if (verbose) {
        print(model)
    }
    return(model)
}

split_data <- function(data, split_ratio = 0.7, stratified = TRUE) {
    # TODO: Generalise target variable
    if (stratified) {
        # Split with createDataPartition function
        indexes <- createDataPartition(
            data$rating_type,
            p = split_ratio,
            list = FALSE,
            times = 1
        )
        train_data <- data[indexes, ]
        test_data <- data[-indexes, ]
        return(list(train_data, test_data))
    }

    # Split randomly
    if(is.null(data)) {
        stop("The dataframe is empty.")
    }
    tot_rows <- nrow(data)
    indexes <- sample(1:tot_rows, size = 0.8 * nrow(data))
    train_data <- data[indexes, ]
    test_data <- data[-indexes, ]
    return(list(train_data, test_data))
}

evaluate_model <- function(model, train_test) {
    test_data <- train_test[[2]]
    predictions <- predict(model, test_data)
    confusion_matrix <- confusionMatrix(predictions, test_data$rating_type)
    # Return confusion matrix and model
    return(list(confusion_matrix, model))
}
```

## VADER
```{r}
# Get the data VADER
data <- get_data("processed/drug_reviews_ge.csv", "processed/vdf.rds") %>%
  filter_birth_control() %>%
  remove_columns_vader() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)
```

```{r}
# VADER
# Get the data VADER
data <- get_data("processed/drug_reviews_ge.csv", "processed/vdf.rds") %>%
  filter_birth_control() %>%
  remove_columns_vader() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

# Are any of the rows empty? 

# Split 
train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)

# Train and evaluate
result.vader.svm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test, verbose = TRUE, tuneLength = 15, preProcess =  c("center", "scale")) %>%
  evaluate_model(train_test)

result.vader.gbm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test,verbose = TRUE,  tuneLength = 15, method = "gbm") %>%
  evaluate_model(train_test)

# result.vader.nb <- train_test %>%
#   stratified_k_fold_cv(k = 10) %>%
#   train_model(train_test, verbose = TRUE, tuneLength = 0, method = "nbDiscrete", preProcess = c("center", "scale")) %>%
#   evaluate_model(train_test)

result.vader.blr <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "LogitBoost", preProcess = c("center", "scale")) %>%
    evaluate_model(train_test)

# AFINN
# Get data for afinn 
data <- get_data("dataset/drugs_cleaned.csv", "processed/afinn.rds") %>%
  filter_birth_control() %>%
  remove_columns() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

# Split
train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)

# Train and evaluate
result.afinn.svm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test, verbose = TRUE, tuneLength = 15, preProcess =  c("center", "scale")) %>%
  evaluate_model(train_test)

result.afinn.gbm <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "gbm") %>%
    evaluate_model(train_test)

# result.afinn.nb <- train_test %>%
#   stratified_k_fold_cv(k = 10) %>%
#   train_model(train_test, verbose = TRUE, tuneLength = 15, method = "nbDiscrete", preProcess = c("center", "scale")) %>%
#   evaluate_model(train_test)

result.afinn.blr <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "LogitBoost", preProcess = c("center", "scale")) %>%
    evaluate_model(train_test)



# BING
# Get data for bing
data <- get_data("dataset/drugs_cleaned.csv", "processed/bing.rds") %>%
  filter_birth_control() %>%
  remove_columns() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

# Split
train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)

# Train and evaluate
result.bing.svm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test, verbose = TRUE, tuneLength = 15, preProcess =  c("center", "scale")) %>%
  evaluate_model(train_test)

result.bing.gbm <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "gbm") %>%
    evaluate_model(train_test)

# result.bing.nb <- train_test %>%
#   stratified_k_fold_cv(k = 10) %>%
#   train_model(train_test, verbose = TRUE, tuneLength = 15, method = "nbDiscrete", preProcess = c("center", "scale")) %>%
#   evaluate_model(train_test)

result.bing.blr <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "LogitBoost", preProcess = c("center", "scale")) %>%
    evaluate_model(train_test)


# NRC
# Get data for nrc
data <- get_data("dataset/drugs_cleaned.csv", "processed/nrc.rds") %>%
  filter_birth_control() %>%
  remove_columns() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

# Split
train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)

# Train and evaluate
result.nrc.svm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test, verbose = TRUE, tuneLength = 15, preProcess =  c("center", "scale")) %>%
  evaluate_model(train_test)

result.nrc.gbm <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test,  verbose = TRUE, tuneLength = 15, method = "gbm") %>%
    evaluate_model(train_test)

# result.nrc.nb <- train_test %>%
#   stratified_k_fold_cv(k = 10) %>%
#   train_model(train_test, verbose = TRUE, tuneLength = 15, method = "nbDiscrete", preProcess = c("center", "scale")) %>%
#   evaluate_model(train_test)

result.nrc.blr <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "LogitBoost", preProcess = c("center", "scale")) %>%
    evaluate_model(train_test)

# jockers_rinker
# Get data for jockers_rinker
data <- get_data("dataset/drugs_cleaned.csv", "processed/jockers_rinker.rds") %>%
  filter_birth_control() %>%
  remove_columns() %>%
  format_dtypes() %>%
  filter_out_bad_vals()

# Split
train_test <- split_data(data, split_ratio = 0.8, stratified = TRUE)

# Train and evaluate
result.jockers_rinker.svm <- train_test %>%
  stratified_k_fold_cv(k = 10) %>%
  train_model(train_test, verbose = TRUE, tuneLength = 15, preProcess =  c("center", "scale")) %>%
  evaluate_model(train_test)

result.jockers_rinker.gbm <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "gbm") %>%
    evaluate_model(train_test)

# result.jockers_rinker.nb <- train_test %>%
#   stratified_k_fold_cv(k = 10) %>%
#   train_model(train_test, verbose = TRUE, tuneLength = 15, method = "nbDiscrete", preProcess = c("center", "scale")) %>%
#   evaluate_model(train_test)

result.jockers_rinker.blr <- train_test %>%
    stratified_k_fold_cv(k = 10) %>%
    train_model(train_test, verbose = TRUE, tuneLength = 15, method = "LogitBoost", preProcess = c("center", "scale")) %>%
    evaluate_model(train_test)

```

```{r}
# Compile results 
results <- list (
  vader.svm = result.vader.svm,
  vader.gbm = result.vader.gbm,
  # vader.nb = result.vader.nb,
  vader.blr = result.vader.blr,

  afinn.svm = result.afinn.svm,
  afinn.gbm = result.afinn.gbm,
  # afinn.nb = result.afinn.nb,
  afinn.blr = result.afinn.blr,

  bing.svm = result.bing.svm,
  bing.gbm = result.bing.gbm,
  # bing.nb = result.bing.nb,
  bing.blr = result.bing.blr,

  nrc.svm = result.nrc.svm,
  nrc.gbm = result.nrc.gbm,
  # nrc.nb = result.nrc.nb,
  nrc.blr = result.nrc.blr,

  jockers_rinker.svm = result.jockers_rinker.svm,
  jockers_rinker.gbm = result.jockers_rinker.gbm,
  # jockers_rinker.nb = result.jockers_rinker.nb,
  jockers_rinker.blr = result.jockers_rinker.blr
)

# Save results
saveRDS(results, "results/lexicon.rds")
```

```{r}
# Read results
results <- readRDS("resuts/lexicon.rds")

# Create a data frame with the results 

```