
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sentimentr)
library(dplyr)
```

```{r}
extract_sentiment <- function(text_dataset, method) {
    # Get estimated runtime
    sample_size <- 1000
    sample_dataset <- text_dataset[1:sample_size]
    start_time <- Sys.time()
    sentimentr::sentiment_by(sample_dataset, method = method)
    end_time <- Sys.time()

    print((end_time - start_time) * (length(text_dataset) / sample_size))

    # Extract sentiment
    sentiment <- sentimentr::sentiment_by(text_dataset, method = method)

    # Drop element_id column
    sentiment <- sentiment %>%
        select(-element_id)

    # Return sentiment
    return(sentiment)
}
```


```{r}
# Load data
df <- read.csv("dataset/drugs_cleaned.csv")
text <- df$review
```

```{r}
# Vector of sentiments to extract
methods <- c("bing", "afinn", "jockers_rinker", "nrc")
# Extract sentiments and save to file
for (method in methods) {
    print(method)
    sentiment <- extract_sentiment(text, method)
    saveRDS(sentiment, paste0("processed/", method, ".rds"))
}

for (method in methods) {
    # Calculate correlation between sentiment and rating
    sentiment <- readRDS(paste0("processed/", method, ".rds"))
    print(head(sentiment))

    df <- read.csv("dataset/drugs_cleaned.csv")
    # DF keep only Birth Control

    correlation <- cor(sentiment$ave_sentiment, df$rating)
    print(correlation)
}

# Merge clean dataset
df <- read.csv("dataset/drugs_cleaned.csv")
# DF keep only Birth Control
df <- df[df$condition == "Birth Control", ]
```

```{r}
```